version: '3'

services:
  
  webServer:
    image: tpso:tag
    build: 
      context: .
      dockerfile: Dockerfile
    restart: 'always'
    ports:
      - '8080:8080'
    volumes: 
      - ./presentation_layer:/webServer/presentation_layer:website
      - ./application_layer:/webServer/application_layer:website
